CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS uno_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    rounds_played INT NOT NULL,
    winner_id BIGINT,
    CONSTRAINT fk_game_winner FOREIGN KEY (winner_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS uno_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    round_number INT NOT NULL,
    turns_played INT NOT NULL,
    winner_id BIGINT,
    points_scored INT NOT NULL,
    CONSTRAINT fk_round_game FOREIGN KEY (game_id) REFERENCES uno_games(id),
    CONSTRAINT fk_round_winner FOREIGN KEY (winner_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS player_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    score INT NOT NULL,
    CONSTRAINT fk_score_game FOREIGN KEY (game_id) REFERENCES uno_games(id),
    CONSTRAINT fk_score_player FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT uq_score_game_player UNIQUE (game_id, player_id)
);
